def howToplay():
  printNow("=============================WELCOME TO MINDCONTROL================================\n"+   
                  
           "____________________________________RULES___________________________________________\n"+
           "The objective of the game is to break the secret code egenerated by the program in as few turns as possible.\n"+
           "The code consists of a series of random colored pegs. The player will choose the level,of difficulty easy (4 columns)\n"+
           "medium (5 columns), hard (6 columns) The user will have 10 chances to crack the secret code by attempting to duplicate\n"+
           "the exact colors and positions of the secret code. After their attempt the program will display a white, peg on the\n"+ 
           "score guide to indicate if the chosen pegs are in the correct position and the right color. A grey peg on the score guide\n"+
           "will indicate if the chosen pegs are in the correct position. If user guesses all white pegs within 10 tries they win!\n\n"+
           
           "____________________Controls________________________\n"
           "The user will input their choices consecutively using the following keys:\n"
           "R=Red, B=Blue,G=Green, W=White, Y=Yellow, P=Purple")
